- hosts: all
  become: yes
  tasks:
    - name: install httpd
      yum:
        name: httpd
    - name: start httpd
      service:
        name: httpd
        state: started
    - name: install php
      yum:
        name:
          - php
          - php-mysql
      notify: restart httpd
    - name: copy phpinfop
      copy:
        src: phpinfo.php
        dest: /var/www/html/phpinfo.php
    - name: add repository
      yum:
        name: http://dev.mysql.com/get/mysql57-community-release-el6-7.noarch.rpm
    - name: install mysqld
      yum:
        name: 
          - mysql-community-server
          - mysql-community-client
          - mysql-community-common
          - mysql-community-libs
          - mysql-community-libs-compat
        enablerepo: mysql56-community
        disablerepo: mysql57-community
        state: present
    - name: start mysqld
      service:
        name: mysqld
        state: started
        enabled: yes
    - name: install MySQL-python
      yum:
        name: MySQL-python
    - name: set MySQL root password
      no_log: true
      mysql_user:
        login_user: root
        login_password: root
        name: root
        password: root
        check_implicit_admin: yes
        state: present
    - name: create DB
      mysql_db:
        login_user: root
        login_password: root
        name: wordpress
        state: present
        encoding: utf8mb4
    - name: add wordpress user
      no_log: true
      mysql_user:
        login_user: root
        login_password: root
        name: wordpress
        password: wordpress
        priv: 'wordpress.*:ALL'
        state: present
    - name: download wordpress
      get_url:
        url: https://ja.wordpress.org/wordpress-4.4.2-ja.tar.gz
        dest: /tmp/wordpress.tar.gz
    - name: unarchive wordpress
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www/html/ 
        copy: no
    - name: chown wordpress files
      file:
       path: /var/www/html/wordpress/
       owner: apache
       group: apache
       recurse: yes
      notify: restart httpd
  handlers:
     - name: restart httpd
       service: 
         name: httpd
         state: restarted